articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('alldelete/', views.alldelete, name='alldelete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/comments/',views.comments_create, name='comments_create'),
]

articles/views.py
from django.shortcuts import render, redirect
from articles.models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
    articles = Article.objects.all()
    return render(request, 'articles/index.html', {'articles': articles})

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    commnets = article.comment.all()
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : commnets,
    }
    return render(request, 'articles/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    
    context = {'form' : form}
    return render(request, 'articles/create.html', context)

def update(request, pk):
    print(pk)
    article = Article.objects.get(pk=pk)

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES,instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk=article.pk)
        return redirect('articles:detail', pk=article.pk)
    else:
        form = ArticleForm(instance=article)
    
    context = {'form' : form, 'article':article}
    return render(request, 'articles/update.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)
    
def alldelete(request):
    article = Article.objects.all()
    article.delete()
    return redirect('articles:index')
    
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
    return redirect('articles:detail', article.pk)

articles/templates/articles/create.html
{% block content %}
    <h1>CREATE</h1>
    <hr>
    <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content%}

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
    <h1>비밀번호변경</h1>
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="변경하기">
    </form>
    <a href="{% url 'articles:index' %}">[목록보기]</a>
{% endblock content %}

templates/accounts/login.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/jquery.min.js" type="text/javascript" href="./test.js"></script> 
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/snowfall.jquery.js" type="text/javascript" href="./test.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body class="body">
        <div class="display-container">
            <div class="all">
                <div class="title">
                    <h1><span>M</span><span>A</span><span>N</span><span>,</span><span>D</span><span>O</span><span>!</span></h1>
                </div>
                <div class="main_img">
                    <img class="mando1" src="{% static 'accounts/source/img/mando1.png' %}" />
                    <img class="mando2" src="{% static 'accounts/source/img/mand02.png' %}" />
                    <img class="mando3" src="{% static 'accounts/source/img/mando3.png' %}" />
                </div>
                <div class="login-wrapper">
                    <form class="loginform" action="{% url 'accounts:login' %}" method="POST" id="login-form">
                            {% comment %} <input type="text" name="userId" placeholder="이메일">
                            <input type="password" name="userPassword" placeholder="비밀번호"> {% endcomment %}
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="로그인">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

templates/accounts/mainpage.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <script href="./snow.js"></script>
        <title>index.html</title>
    </head>
    <body class="body">
        <div class="display-container">
            <div class="all">
                <div class="title">
                    <h1><span>M</span><span>A</span><span>N</span><span>,</span><span>D</span><span>O</span><span>!</span></h1>
                </div>
                <div class="sub-title my-3">2024 목표설정 서비스</div>
                <div class="main_img">
                    <img class="mando4" src="./image/mando4.png" >
                    <img class="mando5" src="./image/mando5.png">
                    <img class="mando7" src="./image/mando7.png">
                </div>
                <div class="button">
                <a href="login.html"><div class="login_button">로그인</div></a>
                <a href="registerpage.html"><div class="register_button">회원가입</div></a>
                </div>
            </div>
        </div>
    </body>
</html>

templates/accounts/signup.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/jquery.min.js" type="text/javascript" href="./test.js"></script> 
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/snowfall.jquery.js" type="text/javascript" href="./test.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body class="body">
        <div class="display-container">
            <div class="all">
                <div class="title">
                    <h1><span>M</span><span>A</span><span>N</span><span>,</span><span>D</span><span>O</span><span>!</span></h1>
                </div>
                <div class="main_img">
                    <img class="mando1" src="{% static 'accounts/source/img/mando1.png' %}" />
                    <img class="mando2" src="{% static 'accounts/source/img/mand02.png' %}" />
                    <img class="mando3" src="{% static 'accounts/source/img/mando3.png' %}" />
                </div>
                <div class="login-wrapper">
                    <form action="{% url 'accounts:signup' %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="회원가입">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정하기">
    </form>
    <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

templates/articles/create.html
{% load static %}
    <h1>CREATE</h1>
    <hr>
    <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content%}

templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="write.css">
        <link rel="stylesheet" type=" text/css" href="style.css">
        <title>man-do!</title>
    </head>
    {% if article.image %}
        <img src="{{ article.image.url }}" >
    {% endif %}
    
    {% if article %}
        <p>글 번호 : {{article.id}}</p>
        <p>글 제목 : {{article.title}}</p>
        <p>글 내용 : {{article.content}}</p>
        <p>생성시각 : {{article.created_at}}</p>
        <p>수정시각 : {{article.updated_at}}</p>
        <hr>
        <a href="{% url 'articles:index' %}">목록보기</a>
        <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
        <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE">
        </form>
        <a href="{%url 'articles:index'%}">[back]</a>
    {% else %}
        <p>No article available.</p>
    {%endif%}

    <h5>Comment</h5>
    <hr>
    <h4>댓글 목록</h4>
    <ul>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
        {% endfor %}
    </ul>
    
    <form action="{ % url 'articles:comments_creaete' article.pk % }" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="작성">
    </form>
{% endblock content%}

<!DOCTYPE html>
<body>
    <form id="myForm" action="/url/" method="POST">
    <div class="display-container">
        <div class="background-image"><img src="page.png" alt="배경"></div>
        <p>나의 목표</p>
        <div class="memo" id="memoContainer">
        <input type="text" id="memoTitle" placeholder="제목을 입력하세요">
        <textarea spellcheck="false" id="memoText" placeholder="나의 목표 "></textarea>
        <input type="file" id="uploadInput" accept="image/*" style="display: none;">
        
        <div class="img-preview"><img src="upload.png" id="uploadTrigger" alt="이미지"></div>
  

    </div>
   
    <!--추후 submit로 변경, sanveAndSend()-->
        <button type="button" onclick="goMando(); ">만두 빚기 </button>
    </div>
</form>

    <script src="write.js"></script>

</body>
</html>

templates/articles/index.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" /> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'articles/css/mando.css' %}" />
        <link rel="stylesheet" href="{% static 'articles/css/style.css' %}" />
        <script src="{% static 'articles/js/mando.js' %}"></script>
        <title>man-do!</title>
    </head>
    <body>
      <div>
        <div class="display-container">
          <div class="background-image"><img src="{% static 'articles/source/img/page.png' %}" alt="배경" /></div>
          <div class="user-mold">
            <span id="user-name">{{ user.name }}</span> <br/><span
              >님의 만두판</span>
          </div>
          <div class="image-grid">
            <img
              id="mold1"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold1')"
            />
            <img
              id="mold2"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold2')"
            />
            <img
              id="mold3"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold3')"
            />
            <img
              id="mold4"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold4')"
            />
            <img
              id="mold5"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold5')"
            />
            <img
              id="mold6"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold6')"
            />
            <img
              id="mold7"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold7')"
            />
            <img
              id="mold8"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold8')"
            />
            <img
              id="mold9"
              src="{% static 'articles/source/img/mold.png' %}"
              alt="만두틀"
              onclick="changeMandoImage('mold9')"
            />
          </div>
        <div id="link">
          <img src="link.png" alt="공유하기" onclick="showLinkAlert();copyLink()" />
        </div>
        <img
          id="link-alert"
          src="{% static 'articles/source/img/link-alert.png' %}"
          alt="링크가복사되었습니다"
          style="display: none"
        />
        <a href="{% url 'articles:alldelete' %}"><div id="reset"><img src="{% static 'articles/source/img/reset.png' %}" alt="리셋" /></div></a>
        <img id="reset-guide" src="{% static 'articles/source/img/reset_quide.png' %}"alt="만두리셋" style="display: none"  />
      </div>
      <a href="{% url 'articles:create' %}"><button  onclick="changeSequentialMandoImage()">글쓰기</button></a>
    </body>

templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
<hr>
<a href="{% url 'articles:detail' article.pk %}">[back]</a>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <title>Re:Try</title>
</head>
<body>
    <div id="nav">
        {% if user.is_authenticated %}
        <a href=" {% url 'accounts:logout' %} ">로그아웃</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원 탈퇴">
        </form>
        <div class="background-image"><img src="page.png" alt="배경" /></div>
        <div class="user-mold">
        <span id="user-name">{{ user }}</span> <br /><span
          >님의 만두판</span
        >
      </div>
        {% else %}
        <br>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}
    </div>
    {% block content%}
    {% endblock content%}
</body>
</html>